version: '3.9'

services:
  main_app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  pdf_worker:
    build: .
    command: python pdf-model.py
    volumes:
      - .:/app
